name: animated_progress_bar
description: A Flutter plugin to show animated progress bar with customization styles.
version: 0.0.3
homepage: https://github.com/mostafa-efafi/animated_progress_bar

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: efafi.mostafa.animated_progress_bar
        pluginClass: AnimatedProgressBarPlugin
      ios:
        pluginClass: AnimatedProgressBarPlugin
      linux:
        pluginClass: AnimatedProgressBarPlugin
      macos:
        pluginClass: AnimatedProgressBarPlugin
      windows:
        pluginClass: AnimatedProgressBarPluginCApi

